#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

GIT_USER=$(git config user.name)
GIT_EMAIL=$(git config user.email)
COMMIT_MSG_FILE=$1

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged '*.php' '*.phtml'| cat)

# Check if we're on a host system or within a Docker container
if ! [ -x "$(command -v php)" ];then
    # REFER TO NOTES WITHIN pre-commit hook #

    (cd "./" && echo "${DIFF}" | \
	    exec 'docker' 'run' '--rm' '-t' "--volume=$PWD:/app" \
	    '--env' 'ENABLE_SENDMAIL=false' '--env' 'PHP_ENABLE_XDEBUG=false' \
	    'magento/magento-cloud-docker-php:7.3-cli' \
	    'vendor/bin/grumphp' 'git:commit-msg' "--git-user=$GIT_USER" "--git-email=$GIT_EMAIL" "$COMMIT_MSG_FILE"
    )
else
    (cd "./" && printf "%s\n" "${DIFF}" | exec 'vendor/bin/grumphp' 'git:commit-msg' "--git-user=$GIT_USER" "--git-email=$GIT_EMAIL" "$COMMIT_MSG_FILE")
fi

